# Generated by Django 4.1.3 on 2023-10-27 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_itinerary_details_itinerary_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
