# Generated by Django 4.1.3 on 2023-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_day_description_alter_itinerary_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
