# Generated by Django 4.1.3 on 2023-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='topspot',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
