# Generated by Django 4.1.3 on 2023-11-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topspot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneymoonSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HoneymoonImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.honeymoonspot')),
            ],
        ),
    ]
