# Generated by Django 4.1.3 on 2023-11-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_day_description_alter_itinerary_details'),
        ('main', '0005_honeymoonspot_honeymoonimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honeymoonimages',
            options={'verbose_name': 'ímage', 'verbose_name_plural': 'ímages'},
        ),
        migrations.AddField(
            model_name='honeymoonimages',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
    ]
