# Generated by Django 4.1.3 on 2023-11-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_day_description_alter_itinerary_details'),
        ('main', '0006_alter_honeymoonimages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeymoonimages',
            name='destination',
        ),
        migrations.AddField(
            model_name='honeymoonspot',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
    ]
