# Generated by Django 4.1.3 on 2023-11-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_honeymoonimages_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeymoonimages',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.honeymoonspot'),
        ),
    ]
